---
version: 2
updates:
  - package-ecosystem: devcontainers
    directories:
      - /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories:
      - /images/**
    ignore:
      - dependency-name: "python"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
    schedule:
      interval: weekly
