---
comictagger: ./**/comictagger/**
context7-mcp: ./**/context7-mcp/**
epub2cbz: ./**/epub2cbz/**
flux-mcp: ./**/flux-mcp/**
github-mcp: ./**/github-mcp/**
humble-cli: ./**/humble-cli/**
kobo-book-downloader: ./**/kobo-book-downloader/**
ebook-metadata: ./**/ebook-metadata/**
terraform-mcp: ./**/terraform-mcp/**
